### ISSUE TITLE
vue传到react的横杠式参数不会自动转为驼峰式吗

### ISSUE THREAD

**Issue by kevinpursuing** [devilwjp/vuereact-combined#10]
如题，外层传入add-product,react组件内部拿到的还是add-product

**Comment by kevinpursuing** [comment]
https://github.com/devilwjp/vuereact-combined/blob/573a30a9beb9466ca117ddbd555f7243a57c1072/src/applyReactInVue.js#L449
我看这里注释掉了，是出于什么考虑呢

**Comment by devilwjp** [comment]
@kevinpursuing 注释的部分只处理dataset，即便打开注释，也无法将`add-product`转为`addProduct`的，之所以不转，是因为react确实可以接收到`add-product`格式的参数，这个和vue的规范是不同的

**Comment by devilwjp** [comment]
如果把所有的参数都转成了驼峰，那么会造成react组件内部需要接受中划线参数的属性接收不到

**Comment by devilwjp** [comment]
@kevinpursuing 你要明确，其实你在使用的是一个react组件，组件内部是任何格式的参数都可以接收到的

**Comment by kevinpursuing** [comment]
> 

主要是vue是做了一层这个转换的， 父vue组件引入子vue组件，外层是中划线，内层会自已转换，而且就前端开发来说，应该很少会有中划线的情况吧？

**Comment by devilwjp** [comment]
@kevinpursuing 只要react是支持的，我就不能随意转换了，你可以考虑包装一个react的HOC，将中划线转换成驼峰。然后再最外层再使用applyReactInVue

**Comment by kevinpursuing** [comment]
是否可以做一个是否转换为驼峰式标志位呢？我理解应该90%的人会选择打开这个标志位吧，因为无论是vue子组件的使用预期或是React的变量规范，都是驼峰吧

**Comment by devilwjp** [comment]
@kevinpursuing react不是的，react是接受任何参数的，比如：
![image](https://user-images.githubusercontent.com/38802722/186109944-15019f0b-51ea-4716-9776-2d6dd295cb88.png)
![image](https://user-images.githubusercontent.com/38802722/186110008-ffc1fdda-8c6a-455d-9bea-df208b8c456c.png)

**Comment by kevinpursuing** [comment]
嗯，其实挺矛盾的，一方面是最好不要动到react的原生属性，另一方面开发者的使用体验，有点难兼顾，我们自己封装下吧
