### ISSUE TITLE
ReactDOM.render is no longer supported in React 18.

### ISSUE THREAD

**Issue by jspradlin1-chwy** [devilwjp/vuereact-combined#11]
When using applyReactInVue, I get the following warning in the console:

> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
This is just a warning, the next version will fix this warning.

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
Fixed in v1.2.7
