### ISSUE TITLE
React components connected to vuex store always re-render on any change to store

### ISSUE THREAD

**Issue by jspradlin1-chwy** [devilwjp/vuereact-combined#12]
Issue: React component that is connected to the vuex store will re-render any time the vuex store changes, even if the properties being changed are not referenced in the react component.

Expected behavior: Only changes to mapped properties (mapStateToProps, mapGettersToProps) should trigger a re-render.

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
According to the design concept of react, the update right of the component should be determined by the component itself, and the shallow equality check or the deep equality check can be processed inside the react component.

And your modification is a shallow equality check, if the state is an object and a subset of the object is modified, it will not trigger an update of the react component.

For example:
```js
const store = new Vuex.Store({
  state: {
    group: {foo: 1}
  },
  mutations: {
    increment (state) {
      state.group.foo++
    }
  }
})

```

**Comment by jspradlin1-chwy** [comment]
@devilwjp 
As per [this](https://stackoverflow.com/questions/40386128/how-does-a-redux-connected-component-know-when-to-re-render) comment:

>    The connect function generates a wrapper component that subscribes to the store. When an action is dispatched, the wrapper component's callback is notified. It then runs your mapState function, and shallow-compares the result object from this time vs the result object from last time (so if you were to rewrite a redux store field with its same value, it would not trigger a re-render). If the results are different, then it passes the results to your "real" component" as props.
>
>   Dan Abramov wrote a great simplified version of connect at ([connect.js](https://gist.github.com/gaearon/1d19088790e70ac32ea636c025ba424e)) that illustrates the basic idea, although it doesn't show any of the optimization work. I also have links to a number of articles on [Redux performance](https://github.com/markerikson/react-redux-links/blob/master/react-performance.md#redux-performance) that discuss some related ideas.

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
I will consider introducing a new solution to introduce vuex, which will be similar to veaury's solution.

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
The quick solution is to expose the state equality check method as a function parameter of connectVuex, which can be customized by the user.

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
I reviewed your commit in detail again, everything is sensible and can be merged into the master branch. Thanks very much!

**Comment by devilwjp** [comment]
@jspradlin1-chwy 
I made better optimizations based on your PR, using `watch` instead of `subscribe`, and using `deep`, which can accurately trigger the update of react components, even if modifying a subset of state objects can trigger an update.

```js
 componentDidMount () {
      this.watch = vuexStore.watch(function() {
        return {...mapStateToProps(vuexStore.state), ...mapGettersToProps(vuexStore.getters)}
      }, (newVal) => {
        this.setState(newVal)
      }, {
        deep: true
      })
    }
```
