### ISSUE TITLE
Uncaught TypeError: children is not a function

### ISSUE THREAD

**Issue by robertmylne** [devilwjp/vuereact-combined#14]
```
export default function App() {
  const { width } = useWindowSize();

  const smallScene = width < 1400;

  return (
    <EmailEditorProvider
      data={initialValues}
      height={'calc(100vh - 72px)'}
      autoComplete
      dashed={false}
    >
      {({ values }) => {
        return (
          <StandardLayout
            compact={!smallScene}
            showSourceCode={true}
          >
            <EmailEditor />
          </StandardLayout>
        );
      }}
    </EmailEditorProvider>
  );
}
```

This is the react code that I am trying to use in vue. It seems to complain about the missing function. Do you know how to solve this, I couldn't see any docs with examples about the child being a function.
```
            <EmailEditorProviderInVue
                :data="initialValues"
                height="calc(100vh - 72px)"
            >
                <StandardLayoutInVue
                    :compact="true"
                    :showSourceCode="true"
                >
                    <EmailEditorInVue />
                </StandardLayoutInVue>
            </EmailEditorProviderInVue>

    components: {
        EmailEditorProviderInVue: applyReactInVue(EmailEditorProvider),
        StandardLayoutInVue: applyReactInVue(StandardLayout),
        EmailEditorInVue: applyReactInVue(EmailEditor)
    },
```

**Comment by devilwjp** [comment]
@robertmylne 
You can refer to this issue (#8 )

**Comment by devilwjp** [comment]
@robertmylne 
I think the react example you provided may be incorrect, it seems that a Consumer component should be nested, such as the following example.

```jsx
const AA = createContext('AA')
<AA.Provider value={111}>
    <AA.Consumer>{(value) => <div>{value}</div>}</AA.Consumer>
</AA.Provider>
```

**Comment by robertmylne** [comment]
Thanks for the response and help.

I couldn't seem to get it working. I think the syntax or something I am doing is incorrect.

The package is here: https://github.com/zalify/easy-email and has a single example which I can't seem to get working as it keeps complaining about "children not being a function" like it is in their example.

Screenshot of the same code below.

Thank you for your time.

![image](https://user-images.githubusercontent.com/10385217/198059368-f4d62019-3a93-4b20-983d-15f162ecc6c1.png)

**Comment by devilwjp** [comment]
@robertmylne 
Using functions as children attributes is not supported temporarily. It will be supported in future versions. It will support the use of scoped slots to be passed in as functions. Now other attributes can support the use of scoped slots to pass functions. Only children are not allowed.

**Comment by devilwjp** [comment]
@robertmylne 
Version 1.2.9 already supports the children of components transformed with `applyReactInVue` is a function.

For example the following react code  
```jsx
// Component FunctionalChildren accepts a children property, and the children property is a function
import FunctionalChildren from "./react_app/FunctionalChildren";
export default funtion () {
  return <FunctionalChildren>{(value) => <div style={{color: 'red'}}>{value}</div>}</FunctionalChildren>
}
```

The code in vue is as follows
```vue
<template>
  <FunctionalChildren>
    <template #children="value">
      <div style="color:red">{{value}}</div>
    </template>
  </FunctionalChildren>
</template>
<script>
import { applyReactInVue } from 'vuereact-combined';
import FunctionalChildren from "./react_app/FunctionalChildren";
export default {
  components: {
    FunctionalChildren: applyReactInVue(FunctionalChildren),
  }
}
</script>
```
