### ISSUE TITLE
请问Vue3只能使用Veaury吗？此项目有计划支持Vue3吗？

### ISSUE THREAD

**Issue by citynook** [devilwjp/vuereact-combined#21]
使用 Veaury 加载的 amis-editor 控件在使用过程中，经常会报错，此问题已提交到 Veaury 的 issues 中。

刚看到此项目，下载使用 applyReactInVue 时 报错。

项目环境：Vite3 + Vue3

**Comment by devilwjp** [comment]
@citynook veaury就是vuereact-combined的vue3版本

**Comment by citynook** [comment]
收到，多谢~~
