### ISSUE TITLE
在React组件内部，this.$vuetify对象无法获取

### ISSUE THREAD

**Issue by stonehank** [devilwjp/vuereact-combined#6]
你好， 我在使用时遇到一个问题，首先我全局使用`$vuetify`，在Vue组件中`this.$vuetify`可以获取到一个对象

然后，在Vue中使用React组件时，当React组件包裹另外Vue组件时，被包裹在内部的Vue组件中`this.$vuetify`在无法获取

最小化案例： [https://codesandbox.io/s/vuereact-combined-notfound-vuetify-4oi8j](https://codesandbox.io/s/vuereact-combined-notfound-vuetify-4oi8j)

**Comment by devilwjp** [comment]
你好，这个情况确实存在，因为每次从react再次使用vue组件时，会是一个全新的vue的实例化，这个问题在vue包囊react的场景中已经被解决，思路是使用了react的portal来代替包囊层，在vue2+中没有portal的概念，但是我们已经找到了解决方案，会在1.1+的版本进行处理  
另外，你demo中的情况是可以通过一个简单的方法解决的，就是将vuetify的实例挂载到Vue的原型中  
````javascript
// main.js
import Vue from "vue";
import App from "./App.vue";
import Vuetify from "vuetify";
Vue.config.productionTip = false;
Vue.use(Vuetify);
// 挂在原型上，使得之后其他Vue的实例化可以获取到
Vue.prototype.$vuetify = new Vuetify();
new Vue({
  render: (h) => h(App)
}).$mount("#app");
````

**Comment by devilwjp** [comment]
@stonehank 期待你的尝试和答复，如果未能达到你的预期，请继续给我留言，谢谢

**Comment by stonehank** [comment]
@devilwjp  vuetify 必须要放在 new Vue() 的options上，它在内部逻辑是`this.$vuetify=$parent.$vuetify || this`(大概是这样)，因此如果挂载到`prototype`也是无法通过`this.$vuetify`获取

我目前是直接挂载到window

![image](https://user-images.githubusercontent.com/26397640/127773686-5178d1e7-f826-4696-bef6-4063462cf5e6.png)

但是还有个问题就是，在React组件内部的所有Vue组件无法通过devtool调试了，例如上图Valine是React组件，内部的所有Vue组件都看不到，应该还是2个Vue实例的问题，感觉2个Vue实例被隔断了

**Comment by devilwjp** [comment]
@stonehank 是的，现在的解决方案中vue依旧是多例模式，react已经是单例模式了，将vue也优化成单例模式正在进行中，可以期待下1.1+版本  
不过关于devtools的问题，虽然也是多例造成的，但是之后即便改成了单例，在devtool里能看到的节点应该和实际还是有出入的，因为会使用模拟类似react portal的方式去实现单例，所以在devtools的节点展示上还是不能做到完全无损的表现

**Comment by devilwjp** [comment]
@stonehank 1.1.0已经发布，看看是否能解决你的所有问题

**Comment by stonehank** [comment]
@devilwjp 试了下1.1.1，完美解决目前的2个问题 👍
